# Generated by Django 2.1.4 on 2018-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
