# Generated by Django 2.1.4 on 2018-12-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_enterprise', '0002_auto_20181229_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store',
        ),
    ]
