# Generated by Django 2.1.4 on 2018-12-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_enterprise', '0003_delete_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(default=7567377),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(default='set.jpg', upload_to='images/'),
        ),
    ]
